---

- hosts: local
  gather_facts: True

  tasks:

    - name: "Get last commit author"
      shell: git log -1 --pretty=format:'%an'
      register: git_log_result

    - set_fact:
        git_last_commit_author: "{{ git_log_result.stdout }}"

    - name: "Stop if CI was last commit author"
      meta: end_play
      when: git_last_commit_author == git_author_name

    - name: "Get list of modified formulas since last commit"
      shell: "git log -m -1 --name-only --pretty=\"format:\" | grep \"Formula/\" | cut -d / -f 2"
      register: git_show_result

    - set_fact:
        git_modified_formulas: "{{ git_show_result.stdout_lines }}"

#    - name: "ensure xcode 11.7 is installed on macos 10.15"
#      shell: "xcode-select -s /Applications/Xcode_11.7.app"
#      when: ansible_distribution_version is version('10.15.0', '>=') and ansible_distribution_version is version('10.16.0', '<')
#      become: true

#    - name: "ensure xcode 12.2 is installed on macos 11.0"
#      shell: "xcode-select -s /Applications/Xcode_12.5.1.app"
#      when: ansible_distribution_version is version('11.0.0', '>=')
#      become: true



    - name: Ensure valet-sh tap is tapped
      homebrew_tap:
        tap: 'valet-sh/core'
        state: present

    - name: Apply workaround for bottle build
      ansible.builtin.lineinfile:
        path: /usr/local/Homebrew/Library/Homebrew/env_config.rb
        insertafter: '    def forbid_packages_from_paths?'
        line:       return false

    - include_tasks: sub-build-bottles.yml
      loop: "{{ git_modified_formulas }}"

#    - name: Build bottles for modified formulas
#      shell: |
#        brew install --build-bottle --formula {{ formula_path }}/{{ item }}
#        brew bottle {{ formula_path }}/{{ item }} --json --force-core-tap --skip-relocation --no-rebuild
#      when: item == "vsh-elasticsearch7.rb"
#      loop: "{{ git_modified_formulas }}"

    - name: Creates build folder
      file:
        path: "{{ build_path }}"
        state: directory

    - name: Move bottles to build folder
      shell: |
        mv *.tar.gz {{ build_path }}
        mv *.json {{ build_path }}
