---

- name: "run 'arch --x86_64 /usr/local/bin/brew install --build-bottle --formula {{ formula_path }}/{{ item }}'"
  shell: "arch --x86_64 /usr/local/bin/brew install --build-bottle --formula {{ formula_path }}/{{ item }}"

- name: "run 'arch --x86_64 /usr/local/bin/brew bottle {{ formula_path }}/{{ item }} --json --force-core-tap --no-rebuild'"
  shell: "arch --x86_64 /usr/local/bin/brew bottle {{ formula_path }}/{{ item }} --json --force-core-tap --no-rebuild"
