name: build

on:
  pull_request:
    paths:
      - 'Formula/**.rb'

jobs:

  build-bottles:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: macOS-latest
    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - uses: actions/checkout@v1

      - name: Install dependencies
        working-directory: .github/ansible
        run: |
          brew doctor || true
          brew update || true
          brew upgrade $(brew outdated --formula -q) || true
          python -m pip install --upgrade pip
          pip install -Iq -r requirements.txt

      - name: Build bottles
        working-directory: .github/ansible
        run: ansible-playbook -vvv playbooks/build-bottles.yml

      - uses: actions/upload-artifact@v1
        with:
          name: build
          path: build


  upload-bottles:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    needs: [build-bottles]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - uses: actions/checkout@v1

      - name: Install dependencies
        working-directory: .github/ansible
        run: |
          python -m pip install --upgrade pip
          pip install -Iq -r requirements.txt

      - uses: actions/download-artifact@v1
        with:
          name: build

      - name: Upload Bottles
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: .github/ansible
        run: ansible-playbook playbooks/upload-bottles.yml


  update-formulas:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    needs: [upload-bottles]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - uses: actions/checkout@v1

      - name: Install dependencies
        working-directory: .github/ansible
        run: |
          python -m pip install --upgrade pip
          pip install -Iq -r requirements.txt

      - uses: actions/download-artifact@v1
        with:
          name: build

      - name: Update Formulas
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: .github/ansible
        run: ansible-playbook playbooks/update-formulas.yml
   
  automerge:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    needs: [update-formulas]
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.12.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

