name: dependencies

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:

  check-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - uses: actions/checkout@v1

      - name: Install dependencies
        working-directory: .github/ansible
        run: |
          python -m pip install --upgrade pip
          pip install -Iq -r requirements.txt

      - name: Check dependencies
        working-directory: .github/ansible
        run: ansible-playbook playbooks/check-dependencies.yml
        
      - uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}
          base: master
          commit-message: Trigger bottle rebuild
          committer: valet.sh dependency bot <noreply@valet.sh>
